server:
    port: 8080
management:
    endpoints:
        cors:
          allowed-origins: "*"
        web:
          exposure:
              include: "health"
        endpoint:
            health:
              show-details: NEVER
http:
    request:
      verify: "http://connector.melgar.link/v1/verify/keys"
      stack: "http://connector.melgar.link/v1/orange/create"
      status-infra: "http://connector.melgar.link/v1/orange/status"
